import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto, Roboto_Slab } from 'next/font/google'

const inter = Roboto_Slab({
    weight: ['300', '400', '500', '700'],
    subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en' className='scroll-smooth'>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
